// Bundles the MCP Apps client (src/widgets/quote-card-client.ts) into a single
// self-contained IIFE and writes it as a TS string constant that quote-card.ts
// inlines into the mcp-app resource variant. Runs before tsc in the build.
import esbuild from "esbuild";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const entry = join(root, "src", "widgets", "quote-card-client.ts");
const out = join(root, "src", "widgets", "quote-card-client-bundle.ts");

const result = await esbuild.build({
  entryPoints: [entry],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2020",
  minify: true,
  write: false,
  legalComments: "none",
});

const code = result.outputFiles[0].text;
const banner = "// GENERATED by scripts/build-widget.mjs — do not edit. Run `npm run build`.\n";
// Annotate `: string` so tsc emits a tiny .d.ts (declare const … : string) instead
// of inlining the entire 300KB string literal as the const's inferred type.
writeFileSync(out, `${banner}export const APP_CLIENT_BUNDLE: string = ${JSON.stringify(code)};\n`);
console.error(`[build-widget] bundled MCP Apps client: ${code.length} bytes`);
