// Bundles the MCP Apps clients into self-contained IIFE strings that the widget
// modules inline into their mcp-app resource variants. Runs before tsc.
//
//   src/widgets/quote-card-client.ts    → quote-card-client-bundle.ts    (APP_CLIENT_BUNDLE)
//   src/widgets/bookings-card-client.ts → bookings-card-client-bundle.ts (BOOKINGS_APP_CLIENT_BUNDLE)
import esbuild from "esbuild";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const targets = [
  { entry: "quote-card-client.ts", out: "quote-card-client-bundle.ts", name: "APP_CLIENT_BUNDLE" },
  { entry: "bookings-card-client.ts", out: "bookings-card-client-bundle.ts", name: "BOOKINGS_APP_CLIENT_BUNDLE" },
];

for (const t of targets) {
  const entry = join(root, "src", "widgets", t.entry);
  const out = join(root, "src", "widgets", t.out);

  const result = await esbuild.build({
    entryPoints: [entry],
    bundle: true,
    format: "iife",
    platform: "browser",
    target: "es2020",
    minify: true,
    write: false,
    legalComments: "none",
  });

  const code = result.outputFiles[0].text;
  const banner = "// GENERATED by scripts/build-widget.mjs — do not edit. Run `npm run build`.\n";
  // Annotate `: string` so tsc emits a tiny .d.ts (declare const … : string) instead
  // of inlining the entire string literal as the const's inferred type.
  writeFileSync(out, `${banner}export const ${t.name}: string = ${JSON.stringify(code)};\n`);
  console.error(`[build-widget] bundled ${t.entry}: ${code.length} bytes`);
}
