import {readFileSync,writeFileSync} from 'node:fs';
const pkg=JSON.parse(readFileSync(new URL('../package.json',import.meta.url),'utf8'));
writeFileSync(new URL('../src/version.ts',import.meta.url),`// Generated by scripts/sync-version.mjs from package.json.\nexport const PACKAGE_VERSION = ${JSON.stringify(pkg.version)};\n`);
